
 --https://www.youtube.com/watch?v=XYTTHY50Swo
CREATE TABLE RUTA(
 ID int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
 NOMBRE VARCHAR(100) NOT NULL
)

CREATE TABLE RUTA2(
 ID SERIAL NOT NULL,
 NOMBRE VARCHAR(100) NOT NULL
)


ALTER TABLE RUTA2
 add constraint pkRuta2
 primary key(ID);

 

ALTER TABLE RUTA
 add constraint pkRuta
 primary key(ID);

 
 CREATE TABLE RUTA_DETALLE(
 ID INT NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
 RUTA INT NOT NULL,
 ORIGEN INT NOT NULL,
 DESTINO INT NOT NULL
)


ALTER TABLE RUTA_DETALLE
 add constraint pkRutaDetalle
 primary key(ID);
 

alter table RUTA_DETALLE
add constraint fkRutaDetalleRuta
foreign key (RUTA)
references RUTA (ID);



